apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sandaga-backend-dev
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - sandaga-dev
  selector:
    matchLabels:
      app: sandaga-backend
      monitoring: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: env
          replacement: dev
        - targetLabel: service
          replacement: api
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sandaga-backend-prod
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - sandaga-prod
  selector:
    matchLabels:
      app: sandaga-backend
      monitoring: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: env
          replacement: prod
        - targetLabel: service
          replacement: api
