grafana:
  enabled: true
  adminUser: admin
  adminPassword: change-me-monitoring
  service:
    type: NodePort
    nodePort: 32300
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false

prometheus:
  service:
    type: NodePort
    nodePort: 32301
  prometheusSpec:
    retention: 15d
    scrapeInterval: 30s
    evaluationInterval: 30s

alertmanager:
  service:
    type: NodePort
    nodePort: 32303
